window.addEventListener("message", (event) => {
  if (event.data?.type !== "GENERATE_PDF") return;

  try {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ orientation: "landscape" });
    const payload = event.data.payload;

    // Title
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Smart Scraper - Extracted Data", 14, 15);

    // Metadata
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    const metaY = 22;
    if (payload.pageTitle) doc.text(`Page: ${payload.pageTitle.substring(0, 100)}`, 14, metaY);
    if (payload.url) doc.text(`URL: ${payload.url.substring(0, 120)}`, 14, metaY + 5);
    doc.text(`Type: ${payload.siteType} | Exported: ${payload.timestamp || new Date().toISOString()}`, 14, metaY + 10);

    doc.setTextColor(0);

    // Table
    const rows = payload.rows || [];
    if (rows.length > 1) {
      const headers = rows[0];
      const body = rows.slice(1).map(row =>
        row.map(cell => {
          const str = String(cell ?? "");
          // Truncate long cells for PDF readability
          return str.length > 150 ? str.substring(0, 147) + "..." : str;
        })
      );

      doc.autoTable({
        head: [headers],
        body: body,
        startY: metaY + 16,
        styles: {
          fontSize: 7,
          cellPadding: 2,
          overflow: "linebreak",
          lineWidth: 0.1
        },
        headStyles: {
          fillColor: [26, 115, 232],
          textColor: 255,
          fontStyle: "bold",
          fontSize: 8
        },
        alternateRowStyles: {
          fillColor: [245, 247, 250]
        },
        margin: { left: 14, right: 14 },
        tableWidth: "auto"
      });
    } else if (rows.length === 1) {
      doc.setFontSize(10);
      doc.text("No data rows found.", 14, metaY + 16);
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(150);
      doc.text(
        `Page ${i} of ${pageCount} | Generated by Smart Web Scraper`,
        14,
        doc.internal.pageSize.height - 8
      );
    }

    const pdfDataUri = doc.output("datauristring");
    event.source.postMessage({ type: "PDF_READY", pdfDataUri }, "*");
  } catch (err) {
    event.source.postMessage({ type: "PDF_ERROR", error: err.message }, "*");
  }
});
