if (typeof MSG === "undefined") {
  var MSG = {
    SCRAPE_REQUEST: "SCRAPE_REQUEST",
    DETECT_SITE_TYPE: "DETECT_SITE_TYPE",
    SCRAPE_RESULT: "SCRAPE_RESULT",
    SITE_TYPE_RESULT: "SITE_TYPE_RESULT",
    DOWNLOAD_FILE: "DOWNLOAD_FILE",
    GENERATE_PDF: "GENERATE_PDF",
    PDF_READY: "PDF_READY"
  };
}
